// heroes-tour-react/src/containers/hero-manage/hero-manage.js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';

import { addHero, deleteHero, updateHero, selectHero, unselectHero } from '../../redux/action';
import { EditableItem, AddItem, HeroDetail } from '../../component';

class HeroManage extends Component {
    componentWillUnmount() {
        this.props.unselectHero();
    }
    render() {
        const { heroes, msgs, curHeroId, updateHero, addHero, deleteHero, selectHero, unselectHero } = this.props;
        let heroDetail = '';
        if (curHeroId !== -1) {
            const MATCH_ALL = 0;
            let curHero = {
                name: '',
                id: -1
            };
            let relateMessages = [];
            heroes.forEach(hero => {
                if (hero.id === curHeroId) {
                    curHero = hero;
                }
            });
            msgs.forEach(msg => {
                if (msg.addressee === MATCH_ALL) {
                    relateMessages.push(msg);
                }
                if (msg.addressee === curHeroId) {
                    relateMessages.push(msg);
                }
            });
            heroDetail = <HeroDetail
            hero={curHero}
            msgs={relateMessages}
            updateHero={updateHero}
            unselectHero={unselectHero}
            />;
        }
        const heroItems = heroes.map(hero => (
            <EditableItem
            key={hero.id}
            id={hero.id}
            name={hero.name}
            addHero={addHero}
            deleteHander={deleteHero}
            selectHander={selectHero}
            />
        ));
        return (
            <div>
                <ul className="hero-list-container">
                    <AddItem addBtnCallback={addHero}/>
                    {heroItems}
                </ul>
                {heroDetail}
            </div>
        );
    }
}

const mapStateToProps = (state, ownProps) => ({
    heroes: state.heroes,
    msgs: state.msgs,
    curHeroId: state.curHeroId
});

const mapDispatchToProps = (dispatch, ownProps) => ({
    addHero: bindActionCreators(addHero, dispatch),
    deleteHero: bindActionCreators(deleteHero, dispatch),
    updateHero: bindActionCreators(updateHero, dispatch),
    selectHero: bindActionCreators(selectHero, dispatch),
    unselectHero: bindActionCreators(unselectHero, dispatch)
});

export default connect(mapStateToProps, mapDispatchToProps)(HeroManage);

// hero-tour-vue/src/page/admin/children/hero-manage.vue
<template>
<div>
    <ul class="default-list-container">
      <AddItem :addBtnCallback="addHero"/>
      <EditableItem
      v-for="hero in heroes"
      :key="hero.id"
      :id="hero.id"
      :name="hero.name"
      :delBtnCallback="deleteHero"
      @selectItem="selectHero"
      />
    </ul>
    <div class="hero-detail-panal" v-if="selectedHeroId!==-1">
      <HeroDetail
      :name="selectedHeroName"
      :id="selectedHeroId"
      :receiveMsg="receiveMsg"
      :save="modifyHero"
      :back="back"
      />
    </div>
</div>
</template>

<script>
import { mapMutations } from 'vuex'
import {AddItem, EditableItem, HeroDetail} from '../../../components'
import {ADD_HERO, DELETE_HERO, MODIFY_HERO} from '../../../vuex/constant'
export default {
  data: function () {
    return {
      selectedHeroId: -1
    }
  },
  computed: {
    heroes: function () {
      return this.$store.state.heroes
    },
    selectedHeroName: function () {
      let name = ''
      if (this.selectedHeroId === -1) {
        return name
      }
      this.$store.state.heroes.forEach(hero => {
        if (hero.id === this.selectedHeroId) {
          name = hero.name
        }
      })
      return name
    },
    receiveMsg: function () {
      let receiveMsg = []
      this.$store.state.msgs.forEach(message => {
        if (message.addressee === 0) {
          receiveMsg.push(message)
        }
        if (message.addressee === this.selectedHeroId) {
          receiveMsg.push(message)
        }
      })
      return receiveMsg
    }
  },
  components: {
    AddItem,
    EditableItem,
    HeroDetail
  },
  methods: {
    ...mapMutations({
      deleteHero: DELETE_HERO,
      addHero: ADD_HERO,
      modifyHero: MODIFY_HERO
    }),
    selectHero: function (heroId) {
      this.selectedHeroId = heroId
    },
    back: function () {
      this.selectedHeroId = -1
    }
  }
}
</script>

<style>
.hero-detail-panal{
  width: 400px;
  display: inline-block;
  vertical-align: top;
}
</style>
