// heroes-tour-vue/src/page/admin/children/crisis-manage.vue
<template>
<div>
    <ul class="default-list-container">
      <AddItem :addBtnCallback="addCrisis"/>
      <EditableItem
      v-for="crisis in crisisLibary"
      :key="crisis.id"
      :id="crisis.id"
      :name="crisis.name"
      :delBtnCallback="deleteCrisis"
      :checkCallback="selectCrisis"
      />
    </ul>
    <div class="search-panel">

    </div>
</div>
</template>

<script>
import { mapMutations } from 'vuex'
import {AddItem, EditableItem} from '../../../components'
import {ADD_CRISIS, DELETE_CRISIS, MODIFY_CRISIS} from '../../../vuex/constant'
export default {
  data: function () {
    return {
      selectedCrisisId: null
    }
  },
  computed: {
    crisisLibary: function () {
      return this.$store.state.crisisLibary
    }
  },
  components: {
    AddItem,
    EditableItem
  },
  methods: {
    ...mapMutations({
      deleteCrisis: DELETE_CRISIS,
      addCrisis: ADD_CRISIS,
      modifyCrisis: MODIFY_CRISIS
    }),
    selectCrisis: function (id) {
      this.selectedCrisisId = id
    }
  }
}
</script>

<style>

</style>

// heroes-tour-react/src/containers/crisis-manage/crisis-manage.js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';

import { AddItem, EditableItem } from '../../component';

import { addCrisis, deleteCrisis, selectCrisis, unselectHero } from '../../redux/action';

class CrisisManage extends Component {
    componentWillUnmount() {
        this.props.unSelectCrisis();
    }
    render() {
        const { crisisLibary, addCrisis, deleteCrisis, selectCrisis } = this.props;
        const crisisItems = crisisLibary.map(crisis => (
            <EditableItem
            key={crisis.id}
            name={crisis.name}
            id={crisis.id}
            deleteHander={deleteCrisis}
            selectHander={selectCrisis}
            />
        ));
        return (
            <ul className="hero-list-container">
                <AddItem addBtnCallback={addCrisis} />
                {crisisItems}
            </ul>
        );
    }
}

const mapStateToProps = (state, ownProps) => ({
    crisisLibary: state.crisisLibary
});

const mapDispatchToProps = (dispatch, ownProps) => ({
    addCrisis: bindActionCreators(addCrisis, dispatch),
    deleteCrisis: bindActionCreators(deleteCrisis, dispatch),
    selectCrisis: bindActionCreators(selectCrisis, dispatch),
    unSelectCrisis: bindActionCreators(unselectHero, dispatch)
});

export default connect(mapStateToProps, mapDispatchToProps)(CrisisManage);
