// hero-tour-vue/src/page/admin/admin.vue
<template>
<div>
    <nav class="manage-nav-container">
    <router-link to="/admin/dashboard" active-class="active">Dashboard</router-link>
    <router-link to="/admin/crisis-manage" active-class="active">CrisisManage</router-link>
    <router-link to="/admin/hero-manage" active-class="active">HeroManage</router-link>
    <router-link to="/admin/message-center" active-class="active">MessageCenter</router-link>
    </nav>
    <router-view/>
</div>
</template>

<script>
export default {
  computed: {
    isLogin: function () {
      return this.$store.state.loginStatus
    }
  },
  beforeRouteEnter: function (to, from, next) {
    next(vm => {
      if (!vm.isLogin) {
        vm.$router.push({
          path: '/login',
          query: { redirect: to.fullPath }
        })
      }
    })
  }
}
</script>

<style>
.manage-nav-container {
    height: 33px;
    padding-left: 10px;
    border-bottom: 1px solid #ddd;
}

.manage-nav-container a {
    display: inline-block;
    padding: 4px 8px;
    text-decoration: none;
    color: #333;
}

.manage-nav-container a.active {
    border-width: 4px 1px 1px 1px;
    border-style: solid;
    border-color: #0099ff #ddd #fff #ddd;
    border-radius: 6px 6px 0 0;
}

/*英雄管理*/
.manage-panel-container {
    width: 400px;
    margin-left: 15px;
    margin-right: 15px;
    display: inline-block;
}
</style>

// heroes-tour-react/src/admin/index.js
import React, { Component } from 'react';

import { NavLink } from 'react-router-dom';
import { Route, Switch, Redirect } from 'react-router';

import Dashboard from './component/dashboard';
import CrisisManage from './component/crisis-manage';
import HeroManage from './component/hero-manage';
import MessageCenter from './component/message-center';

import './admin.css';

export default class Admin extends Component {
    render() {
        const { isLogin } = this.props;
        return (
            <div>
        		<nav className="manage-nav-container">
        			<NavLink to="/admin/dashboard" activeClassName="active">Dashboard</NavLink>
					<NavLink to="/admin/crisis-manage" activeClassName="active">CrisisManage</NavLink>
					<NavLink to="/admin/hero-manage" activeClassName="active">HeroManage</NavLink>
					<NavLink to="/admin/message-center" activeClassName="active">MessageCenter</NavLink>
        		</nav>
        		<Switch>
	        		<Route path="/admin/dashboard" component={Dashboard} />
	                <Route path="/admin/crisis-manage" component={CrisisManage} />
	                <Route path="/admin/hero-manage" component={HeroManage} />
	                <Route path="/admin/message-center" component={MessageCenter} />
        			<Redirect extra to="/admin/dashboard" />
                </Switch>
        	</div>
        );
    }
}
