// heroes-tour/src/app/compose/compose.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import Hero from '../model/hero';
import { HeroService } from './../service/hero.service';
import Message from './../model/message';
import { MessageService } from './../service/message.service';

@Component({
  selector: 'app-compose',
  templateUrl: './compose.component.html',
  styleUrls: ['./compose.component.css']
})
export class ComposeComponent implements OnInit {
  message: string;
  addressee: Hero = { name: 'All', id: 0 };
  heroes: Hero[];
  private unsbuscribe: () => void;
  constructor(
    private router: Router,
    private heroService: HeroService,
    private msgService: MessageService
  ) {
    this.heroService.getHeroes().subscribe((heroes: Hero[]) => {
      this.heroes = [this.addressee].concat(heroes);
    });
  }
  sendMessage(): void {
    this.msgService.addMessage(this.message, undefined, this.addressee.id);
  }
  close(): void {
    this.router.navigate([{ outlets: { popup: null } }]);
  }
  ngOnInit() {
  }

}

<div class="message-container">
    <span class="close-icon" (click)="close()">X</span>
    <div class="form-section">
        <span class="message-label">To:</span>
        <select class="hero-list" [(ngModel)]="addressee">
        <ng-container *ngFor="let hero of heroes">
          <option [ngValue]="hero">
            {{hero.name}}
          </option>
        </ng-container>
      </select>
    </div>
    <div class="form-section">
        <span class="message-label">Info:</span>
        <textarea class="message-input" cols="30" rows="10" [(ngModel)]="message"></textarea>
    </div>
    <div class="edit-container">
        <button (click)="sendMessage()">Send</button>
        <button (click)="close()">Cancel</button>
    </div>
</div>

// heroes-tour-react/src/containers/compose/index.js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux'
import { AddressList } from '../../component';
import { addMessage, hideContactPanel } from '../../redux/action';

import './compose.css';

class Compose extends Component {
    constructor() {
        super();
        this.addressInput = null;
        this.uploadAdress = this.uploadAdress.bind(this);
        this.send = this.send.bind(this);
    }
    uploadAdress(input) {
        this.addressInput = input;
    }
    send() {
        const { addMessage } = this.props;
        const author = this.props.isLogin ? 'admin' : 'visitor';
        addMessage(this.msgInput.value, author, this.addressInput.value);
        this.msgInput.value = '';
    }
    render() {
        const { heroes, showContact, hideContactPanel } = this.props;
        if (showContact) {
            return (
                <div className="message-container">
                <span className="close-icon" onClick={hideContactPanel}><i class="fa fa-times" aria-hidden="true"></i></span>
                <div className="form-section">
                    <span className="message-label">To:</span>
                    <AddressList heroes={heroes} uploadAdress={this.uploadAdress}/>
                </div>
                <div className = "form-section" >
                    <span className="message-label">Info:</span>
                    <textarea
                    className = "message-input"
                    cols = "30"
                    rows = "10"
                    ref={(textarea) => this.msgInput = textarea}>
                    </textarea> 
                </div>
                <div className = "edit-container" >
                    <button onClick={this.send}>Send</button>
                    <button onClick={hideContactPanel}>Cancel</button>
                </div>
            </div>
            );
        } else {
            return null;
        }
    }
}

const mapStateToProps = (state, ownProps) => ({
    heroes: state.heroes,
    showContact: state.showContact,
    isLogin: state.isLogin
});

const mapDispatchToProps = (dispatch, ownProps) => bindActionCreators({ addMessage, hideContactPanel }, dispatch);
export default connect(mapStateToProps, mapDispatchToProps)(Compose);
