// heroes-tour/src/app/admin/message-center/message-center.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs/Observable';

import Message from './../../model/message';
import { MessageService } from './../../service/message.service';
import Hero from '../../model/hero';
import { HeroService } from './../../service/hero.service';

@Component({
  selector: 'app-message-center',
  templateUrl: './message-center.component.html',
  styleUrls: ['./message-center.component.css']
})
export class MessageCenterComponent implements OnInit {
  messages: any[];
  private heroes: Hero[];
  constructor(
    private msgService: MessageService,
    private heroService: HeroService
  ) {
    this.heroService.getHeroes().subscribe((heroes: Hero[]) => {
      this.heroes = heroes;
    });
    this.msgService.getMessages()
      .subscribe((msgs: Message[]) => {
        this.messages = [];
        msgs.map((msg: Message) => {
          this.messages.push({
            id: msg.id,
            auth: msg.auth,
            message: msg.message,
            addressee: this.parseAddressee(msg.addressee)
          });
        });
      });
  }
  private parseAddressee(id) {
    if (id === 0) {
      return 'All';
    }
    let addressee = '';
    this.heroes.forEach((hero: Hero) => {
      if (hero.id === id) {
        addressee = hero.name;
      }
    });
    return addressee;
  }

  ngOnInit() {
  }

}

<div>
    <table class="msg-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>FROM</th>
                <th>TO</th>
                <th>MESSAGE</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let message of messages">
                <td>{{message.id}}</td>
                <td>{{message.auth}}</td>
                <td>{{message.addressee}}</td>
                <td>{{message.message}}</td>
            </tr>
        </tbody>
    </table>
</div>

// heroes-tour-react/src/containers/message-center/message-center.js
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { MessageItem } from '../../component';
import './message-center.css';


class MessageCenter extends Component {
    getAddresseeById(id) {
        const heroes = this.props.heroes;
        let addressee = 'unknown';
        if (id === 0) {
            return 'All';
        }
        heroes.forEach(hero => {
            if (hero.id === id) {
                addressee = hero.name;
            }
        });
        return addressee;
    }
    render() {
        const { msgs } = this.props;
        if (msgs.length === 0) {
            return (
                <div>no message</div>
            );
        }
        const messageList = msgs.map(message => {
            let msgInfo = {};
            msgInfo.key = message.id;
            msgInfo.id = message.id;
            msgInfo.auth = message.auth;
            msgInfo.message = message.message;
            msgInfo.addressee = this.getAddresseeById(message.addressee);
            return <MessageItem {...msgInfo} />;
        })
        return (
            <table className="msg-table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>FROM</th>
                        <th>TO</th>
                        <th>MESSAGE</th>
                    </tr>
                </thead>
                <tbody>
                    {messageList}
                </tbody>
            </table>
        );
    }
}

const mapStateToProps = (state, ownProps) => ({
    msgs: state.msgs,
    heroes: state.heroes
});

export default connect(mapStateToProps)(MessageCenter);
